// VentureStay Comprehensive Dataset
window.VENTURE_DATA = {
  heroHighlights: [
    {
      id: 'highlight-india-1',
      number: '01',
      title: 'Spiti Valley & Pin Pass',
      subtitle: 'Trans-Himalayan Tibetan moonscapes & ancient monastery stargazing',
      region: 'Spiti & Ladakh',
      sceneIndex: 0,
      scrollTarget: 0.08,
      coordinates: { lat: 32.2276, lng: 78.0706 },
      image: 'https://images.unsplash.com/photo-1581793745862-99fde7fa73d2?auto=format&fit=crop&w=1920&q=80',
      description: '12,500ft high-altitude desert plateaus, 1000-year-old Ki Gompa, and zero light pollution celestial skies.'
    },
    {
      id: 'highlight-india-2',
      number: '02',
      title: 'Meghalaya Living Roots',
      subtitle: 'Crystalline Umngot emerald river & sacred bio-canopy bridges',
      region: 'Meghalaya & Northeast',
      sceneIndex: 1,
      scrollTarget: 0.29,
      coordinates: { lat: 25.2986, lng: 91.7330 },
      image: 'https://images.unsplash.com/photo-1626621341517-bbf3d9990a23?auto=format&fit=crop&w=1920&q=80',
      description: 'Centuries-old living Ficus elastica root bridges woven over pristine rainforest rivers and misty gorges.'
    },
    {
      id: 'highlight-india-3',
      number: '03',
      title: 'Zanskar & Ladakh Passes',
      subtitle: 'Frozen Chadar river expeditions & untamed cliffside hermitages',
      region: 'Spiti & Ladakh',
      sceneIndex: 2,
      scrollTarget: 0.50,
      coordinates: { lat: 33.4883, lng: 76.8833 },
      image: 'https://images.unsplash.com/photo-1605649487212-47bdab064df8?auto=format&fit=crop&w=1920&q=80',
      description: 'Towering granite massifs, glacial gorges, and sacred high-pass monasteries untouched by modern roads.'
    },
    {
      id: 'highlight-india-4',
      number: '04',
      title: 'Western Ghats & Munnar',
      subtitle: 'Prehistoric evergreen cloud forests & emerald Kurinjimala tea mist',
      region: 'Western Ghats',
      sceneIndex: 3,
      scrollTarget: 0.71,
      coordinates: { lat: 10.0889, lng: 77.0595 },
      image: 'https://images.unsplash.com/photo-1593693397690-362cb9666fc2?auto=format&fit=crop&w=1920&q=80',
      description: 'Ancient cloud-shrouded biodiversity hotspots older than the Himalayas, blanketed in tranquil rolling emerald hills.'
    },
    {
      id: 'highlight-5',
      number: '05',
      title: 'Dark Sky Celestial Ridge',
      subtitle: 'Bortle Class 1 astro-observatories & starlight luxury domes',
      region: 'Himalayas & Highlands',
      sceneIndex: 4,
      scrollTarget: 0.92,
      coordinates: { lat: 34.0522, lng: 77.4219 },
      image: 'https://images.unsplash.com/photo-1506744038136-46273834b3fb?auto=format&fit=crop&w=1920&q=80',
      description: 'Zero light pollution celestial corridors where the Milky Way illuminates glaciated massifs in pristine silence.'
    }
  ],

  accommodations: [
    {
      id: 'stay-india-1',
      title: 'Spiti Kaza Stargazing Stone Sanctuary',
      tagline: 'Centuries-old stone and rammed-earth high Himalayan sanctuary with astronomical skylight',
      type: 'Eco-Lodge',
      region: 'Spiti & Ladakh',
      locationName: 'Kaza, Spiti Valley',
      country: 'India',
      coordinates: { lat: 32.2276, lng: 78.0706 },
      pricePerNight: 165,
      originalPrice: 195,
      rating: 4.98,
      reviewCount: 94,
      bedrooms: 2,
      bathrooms: 2,
      maxGuests: 4,
      verified: true,
      verifiedNotes: 'Zero-waste audit, solar-thermal floor heating, local Spiti women artisan initiative certified',
      images: [
        'https://images.unsplash.com/photo-1581793745862-99fde7fa73d2?auto=format&fit=crop&w=1200&q=80',
        'https://images.unsplash.com/photo-1506744038136-46273834b3fb?auto=format&fit=crop&w=1200&q=80',
        'https://images.unsplash.com/photo-1517824806704-9040b037703b?auto=format&fit=crop&w=1200&q=80',
        'https://images.unsplash.com/photo-1542314831-068cd1dbfeeb?auto=format&fit=crop&w=1200&q=80',
        'https://images.unsplash.com/photo-1518684079-3c830dcef090?auto=format&fit=crop&w=1200&q=80'
      ],
      amenities: ['High-Speed Starlink', 'Open Hearth Fireplace', 'Solar Powered', 'Panoramic Sauna', 'Heated Boot Room'],
      description: 'Perched 3,800 meters above sea level overlooking the winding Spiti River and the illuminated 1000-year-old Ki Gompa, this artisan retreat is built with ancient rammed earth and mountain slate. Offers unparalleled darkness for Bortle Class 1 night-sky astrophotography.',
      highlights: ['Bortle 1 darkness celestial observatory', 'Direct trail to centuries-old Ki Gompa', 'Organic barley and Tibetan herbal dining'],
      ecoCredentials: ['100% Solar-thermal heated', 'Zero single-use plastic certified', 'Local stone mason restoration project'],
      host: {
        name: 'Sonam & Dolma Angmo',
        avatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&w=200&q=80',
        verified: true,
        superhost: true,
        yearsHosting: 5,
        responseRate: '100% within 1 hour'
      }
    },
    {
      id: 'stay-india-2',
      title: 'Meghalaya Living Canopy Forest Treehouse',
      tagline: 'Suspended bamboo and teak sanctuary immersed in subtropical sacred cloud groves',
      type: 'Forest Treehouse',
      region: 'Meghalaya & Northeast',
      locationName: 'Cherrapunji & Mawlynnong',
      country: 'India',
      coordinates: { lat: 25.2986, lng: 91.7330 },
      pricePerNight: 195,
      originalPrice: 240,
      rating: 4.95,
      reviewCount: 82,
      bedrooms: 2,
      bathrooms: 1,
      maxGuests: 4,
      verified: true,
      verifiedNotes: 'Indigenous Khasi tribal stewardship council verified with strict forest conservation standards',
      images: [
        'https://images.unsplash.com/photo-1626621341517-bbf3d9990a23?auto=format&fit=crop&w=1200&q=80',
        'https://images.unsplash.com/photo-1511497584788-87676104235f?auto=format&fit=crop&w=1200&q=80',
        'https://images.unsplash.com/photo-1448375240586-882707db888b?auto=format&fit=crop&w=1200&q=80',
        'https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?auto=format&fit=crop&w=1200&q=80'
      ],
      amenities: ['Suspension Bridge Access', 'Natural Spring Plunge Pool', 'Organic Coffee Bar', 'Night-vision Binoculars Included', 'Solar Microgrid'],
      description: 'Hovering 40 feet above the rainforest floor near the crystalline Umngot River, this eco-structure is engineered using indigenous Khasi living root interlocking methods.',
      highlights: ['Direct private access to double-decker living root bridges', 'Natural limestone cave exploration included', 'Traditional Khasi organic farm-to-table breakfast'],
      ecoCredentials: ['Zero cement footprint', 'Rainwater gravity-harvesting bio-filtration', '100% plastic-free sanctuary'],
      host: {
        name: 'Wanbiang Nongrum',
        avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=200&q=80',
        verified: true,
        superhost: true,
        yearsHosting: 7,
        responseRate: '98% within 2 hours'
      }
    },
    {
      id: 'stay-india-3',
      title: 'Zanskar Glacial Valley Cliff Hermitage',
      tagline: 'Hand-chiseled granite retreat cantilevered over the frozen turquoise Zanskar gorge',
      type: 'Cliffside Hermitage',
      region: 'Spiti & Ladakh',
      locationName: 'Padum, Zanskar Valley',
      country: 'India',
      coordinates: { lat: 33.4883, lng: 76.8833 },
      pricePerNight: 220,
      originalPrice: 275,
      rating: 4.99,
      reviewCount: 63,
      bedrooms: 3,
      bathrooms: 2,
      maxGuests: 6,
      verified: true,
      verifiedNotes: 'High-altitude cold insulation & emergency oxygen concentrator certified',
      images: [
        'https://images.unsplash.com/photo-1605649487212-47bdab064df8?auto=format&fit=crop&w=1200&q=80',
        'https://images.unsplash.com/photo-1518684079-3c830dcef090?auto=format&fit=crop&w=1200&q=80',
        'https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?auto=format&fit=crop&w=1200&q=80',
        'https://images.unsplash.com/photo-1506744038136-46273834b3fb?auto=format&fit=crop&w=1200&q=80'
      ],
      amenities: ['High-Speed Starlink', 'Open Hearth Fireplace', 'Oxygen Concentrators On-Site', 'Private Heated Cedar Tub', 'Trek Pole & Crampon Kit'],
      description: 'Anchored directly into monolithic granite overlooking the winter Chadar ice trek, this ultra-remote luxury hermitage combines traditional Tibetan woodcarving with radiant thermal glass walls.',
      highlights: ['Private spur to Phuktal Cliff Monastery', 'Geothermal stone soaking tub', 'Expedition chef specialized in high-altitude nutrition'],
      ecoCredentials: ['Passive solar Trombe wall heating', 'Glacier melt filtration', 'Carbon-neutral biomass hearth'],
      host: {
        name: 'Tsering Norboo',
        avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=200&q=80',
        verified: true,
        superhost: true,
        yearsHosting: 9,
        responseRate: '100% within 15 mins'
      }
    },
    {
      id: 'stay-india-4',
      title: 'Munnar Cloud Forest Mist Eco-Villa',
      tagline: 'Cantilevered glass & teak pavilion hovering over high Western Ghats tea valleys',
      type: 'Eco-Lodge',
      region: 'Western Ghats',
      locationName: 'Munnar Highlands, Kerala',
      country: 'India',
      coordinates: { lat: 10.0889, lng: 77.0595 },
      pricePerNight: 180,
      originalPrice: 220,
      rating: 4.96,
      reviewCount: 118,
      bedrooms: 2,
      bathrooms: 2,
      maxGuests: 4,
      verified: true,
      verifiedNotes: 'Biodiversity conservation compliance & certified organic micro-plantation',
      images: [
        'https://images.unsplash.com/photo-1593693397690-362cb9666fc2?auto=format&fit=crop&w=1200&q=80',
        'https://images.unsplash.com/photo-1542314831-068cd1dbfeeb?auto=format&fit=crop&w=1200&q=80',
        'https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&w=1200&q=80',
        'https://images.unsplash.com/photo-1470770841072-f978cf4d019e?auto=format&fit=crop&w=1200&q=80'
      ],
      amenities: ['Forest Hot Tub', 'Private Tea Tasting Lounge', 'Fast Fiber Wi-Fi', 'Pour-Over Artisan Coffee Station', 'Solar Heated Plunge Pool'],
      description: 'Suspended in the rolling emerald clouds of the Anamalai mountain range, where Nilgiri Tahr graze outside panoramic master suites. Wake up to swirling silver mist and organic estate-harvested white teas.',
      highlights: ['Private sunrise trek to highest tea peak in South India', 'Herbal Ayurvedic spa terrace', 'Organic estate honey & spice tasting'],
      ecoCredentials: ['100% Hydro & Solar microgrid', 'Zero pesticide buffer zone', 'Rainwater bio-pond retention'],
      host: {
        name: 'Kavitha & Anand Menon',
        avatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&w=200&q=80',
        verified: true,
        superhost: true,
        yearsHosting: 6,
        responseRate: '100% within 1 hour'
      }
    },
    {
      id: 'stay-1',
      title: 'Camel Hill Alpine Sanctuary',
      tagline: 'Secluded luxury panoramic chalet perched on the Dolomite ridge',
      type: 'Alpine Chalet',
      region: 'Alps',
      locationName: 'Cortina d\'Ampezzo',
      country: 'Italy',
      coordinates: { lat: 46.5405, lng: 11.8742 },
      pricePerNight: 320,
      originalPrice: 380,
      rating: 4.96,
      reviewCount: 142,
      bedrooms: 3,
      bathrooms: 2,
      maxGuests: 6,
      verified: true,
      verifiedNotes: 'On-site structural audit & zero-emissions rating certified June 2026',
      images: [
        'https://images.unsplash.com/photo-1506744038136-46273834b3fb?auto=format&fit=crop&w=1200&q=80',
        'https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&w=1200&q=80',
        'https://images.unsplash.com/photo-1542314831-068cd1dbfeeb?auto=format&fit=crop&w=1200&q=80',
        'https://images.unsplash.com/photo-1476514525535-07fb3b4ae5f1?auto=format&fit=crop&w=1200&q=80'
      ],
      amenities: ['Private Cedar Hot Tub', 'Panoramic Sauna', 'Open Hearth Fireplace', 'Ski-in / Ski-out', 'High-Speed Starlink', 'Trailhead Access'],
      description: 'Immersed in pristine alpine air beneath jagged limestone spires, Camel Hill Alpine Sanctuary provides an uncompromising fusion of raw stone architecture and warm minimalist luxury.',
      highlights: ['Direct private spur to Tre Cime di Lavaredo trail', 'Handcrafted local larchwood furniture', 'Telescope observatory on roof terrace'],
      ecoCredentials: ['100% Geothermal powered', 'Rainwater reclamation filtration', 'Passive thermal insulation'],
      host: {
        name: 'Matteo Bellini',
        avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=200&q=80',
        verified: true,
        superhost: true,
        yearsHosting: 6,
        responseRate: '100% within 1 hour'
      }
    },
    {
      id: 'stay-2',
      title: 'Havana Rainforest Canopy Lodge',
      tagline: 'Glass-walled retreat suspended 25 meters within protected cloud forest',
      type: 'Forest Treehouse',
      region: 'Rainforest',
      locationName: 'Monteverde Valley',
      country: 'Costa Rica',
      coordinates: { lat: 10.3023, lng: -84.8255 },
      pricePerNight: 245,
      rating: 4.91,
      reviewCount: 98,
      bedrooms: 2,
      bathrooms: 1,
      maxGuests: 4,
      verified: true,
      verifiedNotes: 'Vetted canopy anchor engineering & wildlife corridor compliance',
      images: [
        'https://images.unsplash.com/photo-1511497584788-87676104235f?auto=format&fit=crop&w=1200&q=80',
        'https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?auto=format&fit=crop&w=1200&q=80',
        'https://images.unsplash.com/photo-1571896349842-33c89424de2d?auto=format&fit=crop&w=1200&q=80'
      ],
      amenities: ['Suspension Bridge Access', 'Natural Spring Plunge Pool', 'Organic Coffee Bar', 'Night-vision Binoculars Included', 'Solar Microgrid'],
      description: 'Listen to the rustle of quetzals and howler monkeys from your private open-air cedar deck. Built without felling a single native tree.',
      highlights: ['Suspension bridge walkway entrance', 'Bioluminescent night tours included', 'Direct access to private reserve paths'],
      ecoCredentials: ['Zero tree-felling construction', 'Composting bio-digester', 'Bird-safe UV reflective glass'],
      host: {
        name: 'Sofia & Carlos Mora',
        avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=200&q=80',
        verified: true,
        superhost: true,
        yearsHosting: 8,
        responseRate: '98% within 2 hours'
      }
    },
    {
      id: 'stay-3',
      title: 'Ghump Forest Wilderness Cabin',
      tagline: 'Historic handcrafted stone & timber retreat beside ancient pinewoods',
      type: 'Wilderness Cabin',
      region: 'Highlands',
      locationName: 'Cairngorms National Forest',
      country: 'Scotland',
      coordinates: { lat: 57.2735, lng: -6.2155 },
      pricePerNight: 195,
      originalPrice: 230,
      rating: 4.88,
      reviewCount: 86,
      bedrooms: 2,
      bathrooms: 1,
      maxGuests: 4,
      verified: true,
      verifiedNotes: 'Heritage restoration and wilderness safety compliance inspected 2026',
      images: [
        'https://images.unsplash.com/photo-1448375240586-882707db888b?auto=format&fit=crop&w=1200&q=80',
        'https://images.unsplash.com/photo-1470770841072-f978cf4d019e?auto=format&fit=crop&w=1200&q=80',
        'https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?auto=format&fit=crop&w=1200&q=80'
      ],
      amenities: ['Wood-Burning Stove', 'Cast-Iron Clawfoot Tub', 'Whisky Tasting Corner', 'Pet Friendly', 'Dark Sky Stargazing Deck'],
      description: 'Set amidst Caledonian pine and heather-carpeted hills, Ghump Forest Cabin offers true stillness and rejuvenation with unpolluted dark skies.',
      highlights: ['Designated Dark Sky Discovery Site', 'Private cold-plunge river bend', 'Complimentary local single malt welcome kit'],
      ecoCredentials: ['Local fallen-timber fuel supply', 'Spring-fed gravity water source', 'Zero single-use plastics'],
      host: {
        name: 'Callum MacLeod',
        avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=200&q=80',
        verified: true,
        superhost: true,
        yearsHosting: 5,
        responseRate: '100% within 30 mins'
      }
    },
    {
      id: 'stay-4',
      title: 'Red Mountain Granite Lodge',
      tagline: 'Architectural marvel integrated into sheer volcanic cliffside rock',
      type: 'Cliffside Villa',
      region: 'Rockies',
      locationName: 'Banff Foothills',
      country: 'Canada',
      coordinates: { lat: 51.1784, lng: -115.5708 },
      pricePerNight: 410,
      rating: 4.98,
      reviewCount: 165,
      bedrooms: 4,
      bathrooms: 3,
      maxGuests: 8,
      verified: true,
      verifiedNotes: 'Structural cliff-anchor certification & full avalanche defensive berms verified',
      images: [
        'https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?auto=format&fit=crop&w=1200&q=80',
        'https://images.unsplash.com/photo-1518780664697-55e3ad937233?auto=format&fit=crop&w=1200&q=80',
        'https://images.unsplash.com/photo-1449844908441-8829872d2607?auto=format&fit=crop&w=1200&q=80'
      ],
      amenities: ['Cantilevered Heated Pool', 'Firepit Lounge', 'Executive Chef Kitchen', 'Heated Boot Room', 'Private EV Supercharger'],
      description: 'Anchored directly into crimson granite, this villa features floor-to-ceiling glass walls framing panoramic vistas of alpine peaks and glacier lakes.',
      highlights: ['Heated infinity edge pool hovering over valley', 'Direct private helicopter landing pad access', 'Professional chef kitchen'],
      ecoCredentials: ['100% Solar roof array with Tesla Powerwalls', 'Greywater bio-filter landscaping', 'Quadruple-glazed low-E windows'],
      host: {
        name: 'Evelyn St. Claire',
        avatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&w=200&q=80',
        verified: true,
        superhost: true,
        yearsHosting: 9,
        responseRate: '100% within 1 hour'
      }
    }
  ],

  experienceGuides: [
    {
      id: 'guide-1',
      name: 'Stanzin Dorje',
      title: 'Lead High-Altitude & Snow Leopard Tracker',
      region: 'Spiti & Ladakh',
      country: 'India',
      locationName: 'Leh & Hemis National Park',
      coordinates: { lat: 34.0522, lng: 77.4219 },
      rating: 4.99,
      reviewCount: 96,
      avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=300&q=80',
      heroImage: 'https://images.unsplash.com/photo-1605649487212-47bdab064df8?auto=format&fit=crop&w=1200&q=80',
      pricePerDay: 280,
      yearsExperience: 14,
      spokenLanguages: ['English', 'Ladakhi', 'Hindi', 'Tibetan'],
      certifications: ['IFMGA High-Altitude Guide', 'Wilderness First Responder (WFR)', 'Snow Leopard Conservation Trust Fellow'],
      specialties: ['High-Altitude Winter Expeditions', 'Predator Tracking & Wildlife Photography', 'Glacier Route Finding'],
      bio: 'Born in the high mountain village of Rumbak at 13,000 feet, Stanzin has spent over 14 years leading extreme winter expeditions across the Zanskar and Karakoram ranges.',
      gearIncluded: ['Swarovski 85mm HD Spotting Scopes', 'Satellite InReach Messenger', 'Avalanche Transceivers & Probes', 'Oxygen Pulse Oximeter Kit']
    },
    {
      id: 'guide-2',
      name: 'Daphne Raintree',
      title: 'Rainforest Canopy Ecologist & Ethnobotanist',
      region: 'Meghalaya & Northeast',
      country: 'India',
      locationName: 'Khasi Hills & Cherrapunji',
      coordinates: { lat: 25.2986, lng: 91.7330 },
      rating: 4.97,
      reviewCount: 78,
      avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=300&q=80',
      heroImage: 'https://images.unsplash.com/photo-1626621341517-bbf3d9990a23?auto=format&fit=crop&w=1200&q=80',
      pricePerDay: 240,
      yearsExperience: 11,
      spokenLanguages: ['English', 'Khasi', 'Hindi'],
      certifications: ['Certified Tree Canopy Ropes Master', 'Advanced Wilderness First Aid', 'IUCN Sacred Forests Specialist'],
      specialties: ['Living Root Bridge Engineering', 'Subtropical River Navigation', 'Bioluminescent Night Treks'],
      bio: 'Specializing in canopy bio-acoustics and tribal botanical heritage, Daphne guides deep into pristine gorges inaccessible to standard travelers.',
      gearIncluded: ['High-Angle Climbing Harnesses', 'Bioluminescence Blacklights', 'Waterproof Hydro-packs', 'Emergency GPS Beacon']
    },
    {
      id: 'guide-3',
      name: 'Marco Vane',
      title: 'Dolomites Alpine & Via Ferrata Master',
      region: 'Alps',
      country: 'Italy',
      locationName: 'Cortina d\'Ampezzo',
      coordinates: { lat: 46.5405, lng: 11.8742 },
      rating: 4.98,
      reviewCount: 124,
      avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=300&q=80',
      heroImage: 'https://images.unsplash.com/photo-1506744038136-46273834b3fb?auto=format&fit=crop&w=1200&q=80',
      pricePerDay: 350,
      yearsExperience: 16,
      spokenLanguages: ['English', 'Italian', 'German', 'French'],
      certifications: ['UIAGM / IFMGA Certified Mountain Guide', 'Avalanche Forecaster Level 3', 'Helicopter Rescue Specialist'],
      specialties: ['Via Ferrata Route Optimization', 'High Alpine Rock Traverses', 'Ski Mountaineering'],
      bio: 'Marco has logged more than 400 summits across the jagged limestone walls of the Italian Dolomites and Swiss Valais Alps.',
      gearIncluded: ['Black Diamond Petzl Via Ferrata Kits', 'GORE-TEX Emergency Bivy Sacks', 'Garmin InReach SOS', 'Petzl Sirocco Helmets']
    }
  ],

  weatherAlerts: [
    {
      id: 'alert-spiti-avalanche',
      region: 'Spiti & Ladakh',
      stationName: 'Kibber High Plateau Observatory (4,270m)',
      severity: 'CRITICAL',
      headline: 'LEVEL 4 AVALANCHE & -24°C SUB-ZERO WHITEOUT WARNING',
      summary: 'Kunzum & Rohtang high mountain passes closed due to 48-hour gale-force blizzard. Trans-Himalayan satellite check-in mandatory.',
      tempC: -21,
      windSpeed: 68,
      mandatedGear: ['Avalanche Transceiver (457kHz)', 'Thermal Hypothermia Wrap', 'Satellite Messenger']
    },
    {
      id: 'alert-meghalaya-mist',
      region: 'Meghalaya & Northeast',
      stationName: 'Nohkalikai Canyon Station (1,480m)',
      severity: 'ADVISORY',
      headline: 'SUBTROPICAL CANYON FLASH MIST & GORGE SURGE ADVISORY',
      summary: 'Crystalline Umngot river gorge experiencing dense riverbed cloud inversions. Bioluminescent night trails operational with certified guides.',
      tempC: 18,
      windSpeed: 24,
      mandatedGear: ['High-Traction River Boots', 'Headlamps (500+ Lumens)', 'Waterproof Hydro-Sack']
    },
    {
      id: 'alert-zanskar-chadar',
      region: 'Zanskar Gorge',
      stationName: 'Padum Ice Station (3,650m)',
      severity: 'WARNING',
      headline: 'CHADAR ICE HIGHWAY CONSOLIDATION NOTICE',
      summary: 'Sub-zero temperatures holding at -18°C. River ice thickness verified at 38cm along Chadar canyon corridors.',
      tempC: -18,
      windSpeed: 35,
      mandatedGear: ['Crampons & Microspikes', 'Insulated Neoprene Boots', 'Ice Axe & Life-line']
    }
  ],

  signatureExpeditions: [
    {
      id: 'exp-1',
      title: 'The Frozen Zanskar Chadar & Ice Gorge Odyssey',
      tagline: 'Navigate the frozen emerald-blue Zanskar River gorge between sheer 1,000-meter cliffs in sub-zero winter isolation.',
      region: 'Spiti & Ladakh',
      durationDays: 9,
      maxAltitude: '3,850m / 12,630ft',
      difficulty: 'Extreme Alpine',
      groupSize: '4 - 8 Climbers',
      pricePerPerson: 2850,
      coverImage: 'https://images.unsplash.com/photo-1518684079-3c830dcef090?auto=format&fit=crop&w=1200&q=80',
      highlights: ['Walking on gleaming frozen turquoise river ice', 'Centuries-old Phuktal Cliff Monastery visit', 'Certified high-altitude expedition medics included']
    },
    {
      id: 'exp-2',
      title: 'Meghalaya Sacred Groves & Living Root Canopy Crossing',
      tagline: 'Trek through prehistoric subtropical rainforests, emerald river gorges, and ancient Khasi living root bridges.',
      region: 'Meghalaya & Northeast',
      durationDays: 6,
      maxAltitude: '1,650m / 5,410ft',
      difficulty: 'Moderate',
      groupSize: '6 - 12 Explorers',
      pricePerPerson: 1650,
      coverImage: 'https://images.unsplash.com/photo-1626621341517-bbf3d9990a23?auto=format&fit=crop&w=1200&q=80',
      highlights: ['Double-decker living root bridges crossing', 'Umngot crystal-clear bamboo boat drift', 'Bioluminescent forest night trek']
    }
  ]
};
