// Flight Data for flights.com transparent overlay
window.POPULAR_AIRPORTS = [
  { city: 'New York', code: 'JFK', name: 'John F. Kennedy Intl Airport', country: 'United States' },
  { city: 'London', code: 'LHR', name: 'Heathrow Airport', country: 'United Kingdom' },
  { city: 'New Delhi', code: 'DEL', name: 'Indira Gandhi Intl Airport', country: 'India' },
  { city: 'Mumbai', code: 'BOM', name: 'Chhatrapati Shivaji Maharaj Intl Airport', country: 'India' },
  { city: 'Dubai', code: 'DXB', name: 'Dubai International Airport', country: 'United Arab Emirates' },
  { city: 'Bangkok', code: 'BKK', name: 'Suvarnabhumi Airport', country: 'Thailand' },
  { city: 'Paris', code: 'CDG', name: 'Charles de Gaulle Airport', country: 'France' },
  { city: 'Singapore', code: 'SIN', name: 'Singapore Changi Airport', country: 'Singapore' },
  { city: 'Tokyo', code: 'HND', name: 'Haneda Tokyo Airport', country: 'Japan' },
  { city: 'Istanbul', code: 'IST', name: 'Istanbul Grand Airport', country: 'Turkey' },
  { city: 'Frankfurt', code: 'FRA', name: 'Frankfurt Airport', country: 'Germany' },
  { city: 'Sydney', code: 'SYD', name: 'Sydney Kingsford Smith Airport', country: 'Australia' }
];

window.generateFlightsForRoute = function(fromCode, fromCity, toCode, toCity, basePrice = 450) {
  return [
    {
      id: 'fl-1',
      airline: 'Emirates',
      airlineCode: 'EK',
      flightNumber: 'EK-203',
      fromCode,
      fromCity,
      toCode,
      toCity,
      departureTime: '08:30 AM',
      arrivalTime: '06:45 PM',
      duration: '7h 15m',
      stops: 0,
      price: basePrice,
      cabinClass: 'Economy',
      baggage: '23kg included',
      features: ['In-flight Wi-Fi', 'Free Gourmet Meal', 'USB Power', 'Entertainment Screen']
    },
    {
      id: 'fl-2',
      airline: 'Qatar Airways',
      airlineCode: 'QR',
      flightNumber: 'QR-701',
      fromCode,
      fromCity,
      toCode,
      toCity,
      departureTime: '11:15 AM',
      arrivalTime: '09:50 PM',
      duration: '8h 35m',
      stops: 1,
      stopDetails: '1h 20m layover in Doha',
      price: Math.round(basePrice * 0.88),
      cabinClass: 'Economy',
      baggage: '25kg included',
      features: ['World-class Dining', 'Award-winning Crew', 'Spacious Seating']
    },
    {
      id: 'fl-3',
      airline: 'British Airways',
      airlineCode: 'BA',
      flightNumber: 'BA-178',
      fromCode,
      fromCity,
      toCode,
      toCity,
      departureTime: '06:40 PM',
      arrivalTime: '06:50 AM (+1)',
      duration: '7h 10m',
      stops: 0,
      price: Math.round(basePrice * 1.05),
      cabinClass: 'Economy',
      baggage: '23kg included',
      features: ['Complimentary Drinks', 'Comfort Blanket', 'On-demand movies']
    },
    {
      id: 'fl-4',
      airline: 'Singapore Airlines',
      airlineCode: 'SQ',
      flightNumber: 'SQ-321',
      fromCode,
      fromCity,
      toCode,
      toCity,
      departureTime: '02:00 PM',
      arrivalTime: '11:20 PM',
      duration: '7h 20m',
      stops: 0,
      price: Math.round(basePrice * 1.15),
      cabinClass: 'Economy',
      baggage: '30kg included',
      features: ['Gourmet Cuisine', 'KrisFlyer Wi-Fi', 'Priority Boarding Option']
    },
    {
      id: 'fl-5',
      airline: 'Lufthansa',
      airlineCode: 'LH',
      flightNumber: 'LH-401',
      fromCode,
      fromCity,
      toCode,
      toCity,
      departureTime: '09:20 PM',
      arrivalTime: '10:40 AM (+1)',
      duration: '8h 20m',
      stops: 1,
      stopDetails: '1h 10m layover in Frankfurt',
      price: Math.round(basePrice * 0.82),
      cabinClass: 'Economy',
      baggage: '23kg included',
      features: ['Ergonomic Seats', 'FlyNet Internet', 'German Hospitality']
    }
  ];
};
